alias pip=pip3
alias python=python3
alias i=nvim
alias upgapt='sudo apt update && apt list --upgradable && sudo apt upgrade -y && sudo apt autoremove -y'
alias lg=lazygit
alias tm=tmux
alias tma='tmux attach'
alias bs='browser-sync start --server --files "*"'
alias gia='git add'
alias gic='git commit'
alias gip='git push'
alias targzx='tar -zxvf'
alias targzc='tar -zcvf'
alias tarx='tar -xvf'
alias tarc='tar -cvf'
alias tarbz2x='tar -jxvf'
alias tarbz2c='tar -jcvf'
alias tarxzx='tar -Jxvf'
alias tarxzc='tar -Jcvf'
