alias pip=pip3
alias python=python3
alias i=nvim
alias aptupg='sudo apt update && apt list --upgradable && sudo apt upgrade -y && sudo apt autoremove -y'
alias lg=lazygit
alias fd=fdfind
alias e=exa
alias ea='exa -a'
alias ee='exa -aal'
alias tm=tmux
alias tma='tmux attach'
alias bs='browser-sync start --server --files "*, ./**/*.css, ./**/*.js"'
alias gia='git add'
alias gic='git commit -m'
alias gip='git push'
alias gib='git branch'
alias tarx='tar -xvf'
alias tarc='tar -cvf'
alias tarbz2x='tar -jxvf'
alias tarbz2c='tar -jcvf'
alias tarxzx='tar -Jxvf'
alias tarxzc='tar -Jcvf'
alias targzx='tar -zxvf'
alias targzc='tar -zcvf'
