[cmd_duration]
min_time = 500
show_milliseconds = true
[directory]
truncation_length = 5
[memory_usage]
disabled = false
show_percentage = true
threshold = 85
symbol = "MEM: "
style = "bold dimmed red"
